### ISSUE TITLE
fail build with openssl 1.1.0.f

### ISSUE THREAD

**Issue by sl1pkn07** [janvidar/uhub#41]
```
[ 23%] Building C object CMakeFiles/network.dir/src/network/openssl.c.o
/tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c: In function 'net_ssl_library_shutdown':
/tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c:94:2: warning: 'ERR_remove_state' is deprecated [-Wdeprecated-declarations]
  ERR_remove_state(0);
  ^~~~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /tmp/makepkg/uhub-git/src/uhub/src/system.h:102,
                 from /tmp/makepkg/uhub-git/src/uhub/src/uhub.h:28,
                 from /tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c:20:
/usr/include/openssl/err.h:248:1: note: declared here
 DEPRECATEDIN_1_0_0(void ERR_remove_state(unsigned long pid))
 ^
/tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c: In function 'add_io_stats':
/tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c:109:17: error: dereferencing pointer to incomplete type 'BIO {aka struct bio_st}'
  if (handle->bio->num_read > handle->bytes_rx)
                 ^~
/tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c: In function 'get_ssl_method':
/tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c:131:4: warning: 'TLSv1_method' is deprecated [-Wdeprecated-declarations]
    return TLSv1_method();
    ^~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /tmp/makepkg/uhub-git/src/uhub/src/system.h:102,
                 from /tmp/makepkg/uhub-git/src/uhub/src/uhub.h:28,
                 from /tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c:20:
/usr/include/openssl/ssl.h:1612:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
 ^
/tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c:133:4: warning: 'TLSv1_1_method' is deprecated [-Wdeprecated-declarations]
    return TLSv1_1_method();
    ^~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /tmp/makepkg/uhub-git/src/uhub/src/system.h:102,
                 from /tmp/makepkg/uhub-git/src/uhub/src/uhub.h:28,
                 from /tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c:20:
/usr/include/openssl/ssl.h:1618:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_1_method(void)) /* TLSv1.1 */
 ^
/tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c:135:4: warning: 'TLSv1_2_method' is deprecated [-Wdeprecated-declarations]
    return TLSv1_2_method();
    ^~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from /tmp/makepkg/uhub-git/src/uhub/src/system.h:102,
                 from /tmp/makepkg/uhub-git/src/uhub/src/uhub.h:28,
                 from /tmp/makepkg/uhub-git/src/uhub/src/network/openssl.c:20:
/usr/include/openssl/ssl.h:1624:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_2_method(void)) /* TLSv1.2 */
 ^
make[2]: *** [CMakeFiles/network.dir/build.make:255: CMakeFiles/network.dir/src/network/openssl.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:331: CMakeFiles/network.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

greetings

**Comment by janvidar** [comment]
These issues are fixed now.
